name: Hanimo
description: "Anime episode tracking app with fun colors"
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_remote_config: ^5.1.4
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.5.0
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.4
  font_awesome_flutter: ^10.7.0
  jikan_api: ^2.2.1
  cloudflare_r2: ^0.0.13
  onesignal_flutter: ^5.2.6
  google_mobile_ads: ^5.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  cached_network_image: ^3.4.1
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  video_player: ^2.8.2
  chewie: ^1.8.0
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.2.0
  device_calendar: ^4.3.2
  timezone: ^0.9.4
  connectivity_plus: ^6.0.5
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.3

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
