// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvq68WZNvr7LnpYdfuycLKigMgU9Y8h1g',
    appId: '1:712581167603:web:d726bcac39abf9233f7a86',
    messagingSenderId: '712581167603',
    projectId: 'hanimo',
    authDomain: 'hanimo.firebaseapp.com',
    storageBucket: 'hanimo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0KjECymDUwsPXeOOeMmTK7fPjzUWxtM8',
    appId: '1:712581167603:android:0fb4569d098958d13f7a86',
    messagingSenderId: '712581167603',
    projectId: 'hanimo',
    storageBucket: 'hanimo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGwwgoNDAJvZuPl_NCq1BrT0YPZxt8dK4',
    appId: '1:712581167603:ios:3b7db4c8eed5c6d23f7a86',
    messagingSenderId: '712581167603',
    projectId: 'hanimo',
    storageBucket: 'hanimo.firebasestorage.app',
    iosClientId: '712581167603-r7e4akvfdnmkon0u5dsit7sui4t2q8pu.apps.googleusercontent.com',
    iosBundleId: 'com.hanimo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGwwgoNDAJvZuPl_NCq1BrT0YPZxt8dK4',
    appId: '1:712581167603:ios:d40082b19018b03e3f7a86',
    messagingSenderId: '712581167603',
    projectId: 'hanimo',
    storageBucket: 'hanimo.firebasestorage.app',
    iosClientId: '712581167603-on59u9e8k2ajvc91e5jlbtvlhi925l29.apps.googleusercontent.com',
    iosBundleId: 'com.hanimo.app',
  );

}